# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

# until generics is finalized
warnings_are_errors: false
sudo: true

env:
  global:
  - KERAS_BACKEND="tensorflow"
  - MAKEFLAGS="-j 2"


matrix:
  include:    
    - dist: xenial

cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip


before_script:
  - python -m pip install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - python -m pip install --upgrade --ignore-installed --user travis keras h5py pyyaml requests Pillow scipy theano
  - R -e 'tensorflow::install_tensorflow()'

before_install:
  - sudo apt-get -y install libnlopt-dev 
  - sudo apt-get update
  - sudo apt-get -y install python3


after_success:
  - Rscript -e 'covr::codecov()'
